#!/usr/bin/env python3
"""
Interactive first-time setup for ArmaDraft.

Creates .env, division_config.json skeleton, and data/ directory.
Does not overwrite existing files without confirmation.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or default


def confirm(label: str) -> bool:
    answer = input(f"{label} [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def write_if_allowed(path: Path, content: str) -> None:
    if path.exists():
        if not confirm(f"{path.name} already exists. Overwrite?"):
            print(f"  Skipped {path.name}")
            return
    path.write_text(content, encoding="utf-8")
    print(f"  Wrote {path.relative_to(ROOT)}")


def main() -> int:
    print("=" * 60)
    print("ArmaDraft — community setup wizard")
    print("=" * 60)
    print()

    data_dir = ROOT / "data"
    data_dir.mkdir(exist_ok=True)
    print(f"  Ensured {data_dir.relative_to(ROOT)}/ exists")

    env_path = ROOT / ".env"
    example_path = ROOT / ".env.example"

    if not env_path.exists():
        print("\n--- Environment (.env) ---")
        token = prompt("Discord bot token (DISCORD_TOKEN)")
        guild_id = prompt("Discord server ID (GUILD_ID)")
        spreadsheet_id = prompt("Google Spreadsheet ID (SPREADSHEET_ID)")
        admin_role = prompt("Admin role ID (ADMIN_ROLE_ID)")
        admin_log = prompt("Admin log channel ID (optional)", "")
        announcements = prompt("Announcements channel ID (optional)", "")
        replacement_role = prompt("Replacement role ID (optional)", "")
        default_locale = prompt("Default locale: en, pt, es", "en")
        snipe_pause = prompt("Bank snipe pause seconds", "1800")

        env_lines = [
            "# Generated by scripts/setup_wizard.py",
            f"DISCORD_TOKEN={token}",
            f"GUILD_ID={guild_id}",
            "",
            f"SPREADSHEET_ID={spreadsheet_id}",
            "GOOGLE_CREDENTIALS_FILE=credentials.json",
            "",
            f"ADMIN_ROLE_ID={admin_role}",
        ]
        if admin_log:
            env_lines.append(f"ADMIN_LOG_CHANNEL_ID={admin_log}")
        if announcements:
            env_lines.append(f"ANNOUNCEMENTS_CHANNEL_ID={announcements}")
        if replacement_role:
            env_lines.append(f"REPLACEMENT_ROLE_ID={replacement_role}")
        env_lines.extend([
            "",
            f"DEFAULT_LOCALE={default_locale}",
            f"BANK_SNIPE_PAUSE_SECONDS={snipe_pause}",
            "",
        ])
        write_if_allowed(env_path, "\n".join(env_lines))
    else:
        print(f"\n  .env already exists — skipping (see {example_path.name} for reference)")

    div_path = ROOT / "division_config.json"
    if not div_path.exists() or confirm("\nCreate or replace division_config.json?"):
        print("\n--- First division ---")
        name = prompt("Division name", "Acuity")
        channel_id = prompt("Discord channel ID for this division")
        sheet_name = prompt("Sheet tab name for draft board", f"{name} Division")
        team_size = int(prompt("Team size (Pokémon per coach)", "10"))
        total_points = int(prompt("Total points per coach", "110"))
        num_coaches = int(prompt("Number of coaches", "16"))
        first_coach = prompt("First coach name (must match Participants sheet)", "")

        config = {
            "divisions": [
                {
                    "name": name,
                    "channel_id": int(channel_id) if channel_id.isdigit() else channel_id,
                    "sheet_name": sheet_name,
                    "team_size": team_size,
                    "total_points": total_points,
                    "tera_captain_points": 30,
                    "pick_time_initial": 14400,
                    "pick_time_second": 7200,
                    "pick_time_final": 3600,
                    "num_coaches": num_coaches,
                    "first_coach": first_coach,
                }
            ]
        }
        write_if_allowed(div_path, json.dumps(config, indent=2) + "\n")

    coaches_path = ROOT / "coaches.json"
    if not coaches_path.exists():
        write_if_allowed(coaches_path, "[]\n")

    creds = ROOT / "credentials.json"
    if not creds.exists():
        print("\n⚠️  Place your Google service account key at credentials.json")
        print("   Share the spreadsheet with the service account email as Editor.")

    print("\n--- Next steps ---")
    print("1. pip install -r requirements.txt")
    print("2. python main.py")
    print("3. /sync_coaches or /start_division in your division channel")
    print("4. See docs/COMMUNITY_SETUP.md for the full checklist")
    print()
    return 0


if __name__ == "__main__":
    os.chdir(ROOT)
    sys.exit(main())
